# Generated by Django 4.0.4 on 2022-05-26 19:43

import account.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('account', '0001_initial'), ('account', '0002_myuser_delete_user'), ('account', '0003_alter_myuser_managers'), ('account', '0004_myuser_is_staff'), ('account', '0005_profile_delete_myuser'), ('account', '0006_alter_profile_image'), ('account', '0007_alter_profile_date_of_birth'), ('account', '0008_profile_bio'), ('account', '0009_profile_url'), ('account', '0010_remove_profile_bio_alter_profile_image'), ('account', '0011_remove_profile_url'), ('account', '0012_alter_profile_image'), ('account', '0013_profile_bio'), ('account', '0014_remove_profile_bio'), ('account', '0015_profile_num_of_hits'), ('account', '0016_alter_profile_user')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='def_avatar/davatar.png', upload_to=account.models.upload_location)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('num_of_hits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
