# Generated by Django 4.0.4 on 2022-04-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(default='urll'),
            preserve_default=False,
        ),
    ]
