# Generated by Django 4.0.4 on 2022-04-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
    ]
