# Generated by Django 4.0.4 on 2022-04-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
