# Generated by Django 4.0.4 on 2022-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_of_hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
