version: "3.8"


services:
  app:
    build: .
    env_file: .env
    volumes:
      - .:/app/
    working_dir: "/app"
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000"
    container_name: django_cont
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0
    volumes:
      - ./my-db:/var/lib/mysql
    env_file: .env
    ports:
      - "3306:3306"
    container_name: django_db

volumes:
  my-db:




