# Generated by Django 4.0.4 on 2022-04-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_content_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date_create',)},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
