# Generated by Django 4.0.4 on 2022-04-29 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_post2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tweet',
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
