# Generated by Django 4.0.4 on 2022-05-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_tweet_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date_edit',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
