# Generated by Django 4.0.4 on 2022-05-06 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
