# Generated by Django 4.0.4 on 2022-05-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0014_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
