# Generated by Django 4.0.4 on 2022-05-22 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0017_alter_tweet_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Post',
        ),
    ]
